runtime: python27
api_version: 1
service: landing
threadsafe: true

handlers:
  - url: /
    static_files: public/index.html
    upload: public/index.html

  - url: '/([^/]+)/'
    static_files: public/\1/index.html
    upload: 'public/[^/]+/index.html' 

  - url: '/en/([^/]+)/'
    static_files: public/en/\1/index.html
    upload: 'public/en/[^/]+/index.html'

  - url: /en/(.*)
    static_files: public/en/\1
    upload: public/en/.*
    
  - url: /(.*)
    static_files: public/\1
    upload: public/(.*)
